---
groups:
  - name: ralch-blog
    jobs:
    - publish

jobs:
  - name: publish
    plan:
      - get: concourse-tasks
      - get: blog.ralch.com
      - get: blog-source
        trigger: true
      - task: generate
        file: concourse-tasks/blog/generate.yml
        params:
          GIT_USERNAME: {{github-bot-name}}
          GIT_EMAIL: {{github-bot-email}}
        input_mapping:
          blog-content: blog.ralch.com
      - put: blog.ralch.com
        params: {repository: blog-website}

resources:
  - name: blog-source
    type: git
    source:
      uri: git@github.com:phogolabs/blog.git
      branch: master
      private_key: {{git-private-key}}

  - name: blog.ralch.com
    type: git
    source:
      uri: git@github.com:ralch/ralch.github.io.git
      branch: master
      private_key: {{git-private-key}}

  - name: concourse-tasks
    type: git
    source:
      uri: https://github.com/phogolabs/concourse-tasks.git
      branch: master
